critterville/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminapp.urls')),
    path('',include('costomer.urls')),
    path('',include('seller.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views
app_name='seller'
urlpatterns = [
    path('sellerhome/<int:id>',views.sellerhome,name='sellerhome'),
    path('updatepetdetail/<int:uid>/<int:pid>',views.updatepetdetail,name='updatepetdetail'),
    path('sellerlogout',views.sellerlogout,name='sellerlogout'),
    path('listed_products/<int:id>',views.listed_products,name='listed_products'),
    path('deletepet/<int:uid>/<int:pid>',views.deletepet,name='deletepet'),
    path('viewpetdetails/<int:uid>/<int:id>',views.viewpetdetails,name='viewpetdetails'),
]

seller/models.py
from django.db import models
from adminapp.models import Category
from costomer.models import SignUp
# Create your models here.

class PetDetails(models.Model):
    Username=models.ForeignKey(SignUp,on_delete=models.CASCADE,default='')
    Name = models.CharField(max_length=250)
    Category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    Breed = models.CharField(max_length=250)
    Gender = models.CharField(max_length=250)
    Age = models.CharField(max_length=250)
    Size = models.CharField(max_length=250)
    Weight = models.CharField(max_length=250)
    Health = models.CharField(max_length=250)
    Location = models.CharField(max_length=250)
    Photo1 = models.ImageField(upload_to='media/',null=True,blank=True)
    Photo2 = models.ImageField(upload_to='media/',null=True,blank=True)
    Contact_No = models.CharField(max_length=10)
    Description = models.TextField(blank=True)
    Price = models.CharField(max_length=250)
    Uploaded_at = models.DateTimeField(auto_now_add=True)
    
    

seller/forms.py
from django import forms
from .models import PetDetails

class PetDetailsForm(forms.ModelForm):
    class Meta():
        model=PetDetails
        fields='__all__'

class UpdateSellerForm(forms.ModelForm):
    class Meta():
        model=PetDetails
        fields='__all__'

seller/views.py
from django.shortcuts import render,redirect
from .forms import PetDetailsForm,UpdateSellerForm
from .models import PetDetails
from costomer . models import SignUp
from django.contrib import messages
from django.contrib.auth import logout as logouts

# Create your views here.
def sellerhome(request,id):
    user=SignUp.objects.get(id=id)

    if request.method=='POST':
        form = PetDetailsForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            username=form.cleaned_data['Username']
            name=form.cleaned_data['Name']
            category=form.cleaned_data['Category']
            breed=form.cleaned_data['Breed']
            gender=form.cleaned_data['Gender']
            age=form.cleaned_data['Age']
            size=form.cleaned_data['Size']
            weight=form.cleaned_data['Weight']
            health=form.cleaned_data['Health']
            location=form.cleaned_data['Location']
            photo1=form.cleaned_data['Photo1']
            photo2=form.cleaned_data['Photo2']
            contactno=form.cleaned_data['Contact_No']
            description=form.cleaned_data['Description']
            price=form.cleaned_data['Price']
            
            tab = PetDetails(Username=username,Name=name,Category=category,Breed=breed,
                                 Gender=gender,Age=age,Size=size,Weight=weight,
                                 Health=health,Location=location,Photo1=photo1,Photo2=photo2,
                                 Contact_No=contactno,Description=description,Price=price)
            tab.save()
            messages.success(request,"")
            return redirect('/listed_products/%s' % user.id)
            
    
    else:
        form = PetDetailsForm()
    return render(request,'sellerhome.html', {'form':form,'user':user})



def updatepetdetail(request,uid,pid):
    user=SignUp.objects.get(id=uid)
    pet=PetDetails.objects.get(id=pid)
    form=UpdateSellerForm(request.POST or None,request.FILES or None,instance=pet)
    if form.is_valid():
        form.save()
        messages.success(request,"")
        return redirect('/viewpetdetails/%s/%s' % (user.id,pet.id))
    else:
        form=UpdateSellerForm(instance=pet)
    return render(request,'updatepetdetail.html',{'form':form,'user':user,'pet':pet})


def listed_products(request,id):
    user=SignUp.objects.get(id=id)
    pet=PetDetails.objects.filter(Username=id)
    return render(request,'listed_products.html',{'pet':pet,'user':user})

def viewpetdetails(request,uid,id):
    user=SignUp.objects.get(id=uid)
    pet=PetDetails.objects.get(id=id)
    return render(request,'viewpetdetails.html',{'pet':pet,'user':user})

def sellerlogout(request):
    logouts(request)
    messages.success(request,"")
    return redirect('/')

def deletepet(request,uid,pid):
    user=SignUp.objects.get(id=uid)
    pet=PetDetails.objects.filter(id=pid)
    pet.delete()
    messages.success(request,"")
    return redirect('/sellerhome/%s' % user.id)

seller/templates/listed_products.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <title>{% block title %}Welcome to Critterville{% endblock %}</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Meyawo main styles -->
	<link rel="stylesheet" href="{% static 'assets/css/meyawo.css' %}">

    
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600&display=swap');

        *{
        font-family: 'Nunito', sans-serif;
        margin:0; padding:0;
        box-sizing: border-box;
        outline: none; border:none;
        text-decoration: none;
        transition: all .2s linear;
        text-transform: capitalize;
        }

        html{
        font-size: 62.5%;
        overflow-x: hidden;
        }

        body{
        background: #eee;
        }

        .container{
        max-width: 1200px;
        margin:0 auto;
        padding:3rem 2rem;
        }

        .container .title{
        font-size: 3.5rem;
        color:#444;
        margin-bottom: 3rem;
        text-transform: uppercase;
        text-align: center;
        }

        .container .products-container{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(30rem, 1fr));
        gap:2rem;
        }

        .container .products-container .product{
        text-align: center;
        padding:3rem 2rem;
        background: #fff;
        box-shadow: 0 .5rem 1rem rgba(0,0,0,.1);
        outline: .1rem solid #ccc;
        outline-offset: -1.5rem;
        cursor: pointer;
        }

        .container .products-container .product:hover{
        outline: .2rem solid #222;
        outline-offset: 0;
        }

        .container .products-container .product img{
        height: 25rem;
        }

        .container .products-container .product:hover img{
        transform: scale(.9);
        }

        .container .products-container .product h3{
        padding:.5rem 0;
        font-size: 2rem;
        color:#444;
        }

        .container .products-container .product:hover h3{
        color:#27ae60;
        }

        .container .products-container .product .price{
        font-size: 2rem;
        color:#444;
        }

        .products-preview{
        position: fixed;
        top:0; left:0;
        min-height: 100vh;
        width: 100%;
        background: rgba(0,0,0,.8);
        display: none;
        align-items: center;
        justify-content: center;
        }

        .products-preview .preview{
        display: none;
        padding:2rem;
        text-align: center;
        background: #fff;
        position: relative;
        margin:2rem;
        width: 40rem;
        }

        .products-preview .preview.active{
        display: inline-block;
        }

        .products-preview .preview img{
        height: 30rem;
        }

        .products-preview .preview .fa-times{
        position: absolute;
        top:1rem; right:1.5rem;
        cursor: pointer;
        color:#444;
        font-size: 4rem;
        }

        .products-preview .preview .fa-times:hover{
        transform: rotate(90deg);
        }

        .products-preview .preview h3{
        color:#444;
        padding:.5rem 0;
        font-size: 2.5rem;
        }

        .products-preview .preview .stars{
        padding:1rem 0;
        font-size: 1.7rem;
        }

        .products-preview .preview .stars i{
        color:#27ae60;
        }

        .products-preview .preview .stars span{
        color:#999;
        }

        .products-preview .preview p{
        line-height: 1.5;
        padding:1rem 0;
        font-size: 1.6rem;
        color:#777;
        }

        .products-preview .preview .price{
        padding:1rem 0;
        font-size: 2.5rem;
        color:#27ae60;
        }

        .products-preview .preview .buttons{
        display: flex;
        gap:1.5rem;
        flex-wrap: wrap;
        margin-top: 1rem;
        }

        .products-preview .preview .buttons a{
        flex:1 1 16rem;
        padding:1rem;
        font-size: 1.8rem;
        color:#444;
        border:.1rem solid #444;
        }

        .products-preview .preview .buttons a.cart{
        background: #444;
        color:#fff;
        }

        .products-preview .preview .buttons a.cart:hover{
        background: #111;
        }

        .products-preview .preview .buttons a.buy:hover{
        background: #444;
        color:#fff;
        }


        @media (max-width:991px){

        html{
            font-size: 55%;
        }

        }

        @media (max-width:768px){

        .products-preview .preview img{
            height: 25rem;
        }

        }

        @media (max-width:450px){

        html{
            font-size: 50%;
        }

        }
    </style>

</head>
<body>
   
<div class="container">

   <h3 class="title">My Pets </h3>

   <div class="products-container">
    {% for pet in pet %}
      <div class="product" data-name="p-1">
        <a href="{% url 'seller:viewpetdetails' user.id pet.id %}"> 
         <img src="{{pet.Photo1.url}}" alt="">
         <h3>{{pet.Name}}</h3>
        </a>
      </div>
    {% endfor %}
    </div>

</div>






<!-- core  -->
<script src="{% static 'assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

<!-- bootstrap 3 affix -->
<script src="{% static 'assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

<!-- Meyawo js -->
<script src="{% static 'assets/js/meyawo.js' %}"></script>



</body>
</html>

seller/templates/sellerhome.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <style>
    .dropdown {
    position: relative;
    display: inline-block;
    }

    .dropdown-content {
    display: none;
    position:absolute;
    width:150px;
    z-index: 1;
    background-color: rgb(202, 191, 191);
    }

    .dropdown:hover .dropdown-content {
    display: block;
    }

    .dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 30px;
    font-size: 16px;
    border: none;
    }

    .dropdown-content a {
    color: white;
    padding: 5px 5px;
    text-decoration: none;
    display: block;
    }

    .dropdown-content a:hover {
    background-color: #f1f1f1;
    }

  </style>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <title>{% block title %}Welcome to Critterville{% endblock %}</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Meyawo main styles -->
	<link rel="stylesheet" href="{% static 'assets/css/meyawo.css' %}">
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

    <!-- Page Navbar -->
    <nav class="custom-navbar" data-spy="affix" data-offset-top="20" style="background-color:rgb(156, 182, 207); height:70px;">
        
            <a class="logo" href="#" style="font-size: 40px; margin-left: 150px;">Critterville</a>         
            <ul class="nav">
                <li class="item">
                    <a class="active-menu" style="font-size: 20px;" href="#">Home</a>
                </li>
                
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="#about" >About Us</a>
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="#contact">Contact Us</a>
                </li>
                <li class="item">
                    <div class="dropdown">
                        <a class="link" style="font-size: 20px;" href="#">Settings</a>
                        <div class="dropdown-content" style="border:1px solid rgb(76, 110, 139);">
                            <a href="{% url 'seller:listed_products' user.id %}" style="font-size: 15px;">View Pets</a>
                            
                            
                        </div>
                    </div>     
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="{% url 'seller:sellerlogout' %}">Logout</a>
                </li>
                
                
            </ul>
            
            <a href="javascript:void(0)" id="nav-toggle" class="hamburger hamburger--elastic" style="margin-right:250px;">
                <div class="hamburger-box" style="color: black;">
                  <div class="hamburger-inner"></div>
                </div>
            </a>
            
           
    </nav><!-- End of Page Navbar -->


 
        

        
<!-- page header -->
<header id="home" class="header" style="background-image: url('static/assets/imgs/wallpaper2.jpg');">            
    <div class="overlay">        
        <br><br><br><br>
            <form action = "" method = "post" enctype="multipart/form-data" 
               style="margin-left: 480px;font-size: 25px;">
            {% csrf_token %}
            <table>
                <tr>{{form.as_table}}</tr>
            </table>
            <br>
            <input type="submit" value="Back" style="margin-left: 250px;">
            <span><input type="submit" value="Save"></span>
        </form> 
        
    </div> 
</header>
<!-- end of page header -->
         
<br><br><br><br>
{% for msg in messages %}
    {{msg}}
{% endfor %}
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
    



    <!-- core  -->
    <script src="{% static 'assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

    <!-- bootstrap 3 affix -->
	<script src="{% static 'assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

    <!-- Meyawo js -->
    <script src="{% static 'assets/js/meyawo.js' %}"></script>
    
</body>
</html>




   

seller/templates/updatepetdetail.html
{% extends 'sellerhome.html' %}
{% load static %}
{% block content %}

<br><br><br>
<br><br><br>

<div style="margin-left: 450px;">
    <div style="border:2px solid grey; width:600px; height:300px; padding-left:30px; padding-top:20px;">
    {% for msg in messages %} 
        {{msg}}
        {% endfor %} 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        <table>
            <tr>
                {{form.as_table}}
            </tr>
        </table>
        <input type="submit" value="Update">
    </form>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br><br> <br><br>   
{% endblock %}

seller/templates/viewpetdetails.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>{% block title %}Welcome to Critterville{% endblock %}</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Meyawo main styles -->
	<link rel="stylesheet" href="{% static 'assets/css/meyawo.css' %}">
     

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600&display=swap');

        *{
        font-family: 'Nunito', sans-serif;
        margin:0; padding:0;
        box-sizing: border-box;
        outline: none; border:none;
        text-decoration: none;
        transition: all .2s linear;
        text-transform: capitalize;
        }

        html{
        font-size: 62.5%;
        overflow-x: hidden;
        }

        body{
        background: #eee;
        }

        .container{
        max-width: 1200px;
        max-height: fit-content;
        margin:0 auto;
        padding:3rem 2rem;
        }

        .container .title{
        font-size: 3.5rem;
        color:#444;
        margin-bottom: 3rem;
        text-transform: uppercase;
        margin-left: 30px;
        }

        .container .title1{
        font-size: 3.5rem;
        color:#4a2491;
        margin-bottom: 3rem;
        text-transform: uppercase;
        margin-left: 30px;
        }

        .container .products-container{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(30rem, 1fr));
        gap:2rem;
        }

        .container .products-container .product{
        text-align: center;
        padding:3rem 2rem;
        background: #fff;
        box-shadow: 0 .5rem 1rem rgba(0,0,0,.1);
        outline: .1rem solid #ccc;
        outline-offset: -1.5rem;
        cursor: pointer;
        }

        .container .products-container .product:hover{
        outline: .2rem solid #222;
        outline-offset: 0;
        }

        .container .products-container .product img{
        height: 25rem;
        }

        .container .products-container .product:hover img{
        transform: scale(.9);
        }

        .container .products-container .product h3{
        padding:.5rem 0;
        font-size: 2rem;
        color:#444;
        }

        .container .products-container .product:hover h3{
        color:#27ae60;
        }

        .container .products-container .product .price{
        font-size: 2rem;
        color:#444;
        }

        .products-preview{
        position: fixed;
        top:0; left:0;
        min-height: 100vh;
        width: 100%;
        background: rgba(0,0,0,.8);
        display: none;
        align-items: center;
        justify-content: center;
        }

        .products-preview .preview{
        display: none;
        padding:2rem;
        text-align: center;
        background: #fff;
        position: relative;
        margin:2rem;
        width: 40rem;
        }

        .products-preview .preview.active{
        display: inline-block;
        }

        .products-preview .preview img{
        height: 50rem;
        }

        .products-preview .preview .fa-times{
        position: absolute;
        top:1rem; right:1.5rem;
        cursor: pointer;
        color:#444;
        font-size: 4rem;
        }

        .products-preview .preview .fa-times:hover{
        transform: rotate(90deg);
        }

        .products-preview .preview h3{
        color:#444;
        padding:.5rem 0;
        font-size: 2.5rem;
        }

        .products-preview .preview .stars{
        padding:1rem 0;
        font-size: 1.7rem;
        }

        .products-preview .preview .stars i{
        color:#27ae60;
        }

        .products-preview .preview .stars span{
        color:#999;
        }

        .products-preview .preview p{
        line-height: 1.5;
        padding:1rem 0;
        font-size: 1.6rem;
        color:#777;
        }

        .products-preview .preview .price{
        padding:1rem 0;
        font-size: 2.5rem;
        color:#27ae60;
        }

        .products-preview .preview .buttons{
        display: flex;
        gap:1.5rem;
        flex-wrap: wrap;
        margin-top: 1rem;
        }

        .products-preview .preview .buttons a{
        flex:1 1 16rem;
        padding:1rem;
        font-size: 1.8rem;
        color:#444;
        border:.1rem solid #444;
        }

        .products-preview .preview .buttons a.cart{
        background: #444;
        color:#fff;
        }

        .products-preview .preview .buttons a.cart:hover{
        background: #111;
        }

        .products-preview .preview .buttons a.buy:hover{
        background: #444;
        color:#fff;
        }


        @media (max-width:991px){

        html{
            font-size: 55%;
        }

        }

        @media (max-width:768px){

        .products-preview .preview img{
            height: 25rem;
        }

        }

        @media (max-width:450px){

        html{
            font-size: 50%;
        }

        }
    </style>



</head>
<body>
   
        <div class="container" style="background-color: rgb(226, 215, 215);">
            <div class="products-container" style="height: 600px;margin-left: 200px;">
                <div class="product" data-name="p-1" style="width: 800px;height: 600px;">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="{{pet.Photo1.url}}" alt="" style="height: 500px;width: 600px;">
                            </div>
                            <div class="item">
                                <img src="{{pet.Photo2.url}}" alt="" style="height: 500px;width: 600px;">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
            <br><br>
            <div style="margin-left: 200px;border:1px solid  white;width:800px;background-color:white;">
                <h1 class="title" style="font-size: 70px;">{{pet.Name}} </h1>
                <h1 class="title">Category:{{pet.Category}}</h1>
                <h1 class="title">Gender:{{pet.Gender}}</h1>
                <h1 class="title">Age:{{pet.Age}}</h1>
                <h1 class="title">Size:{{pet.Size}}</h1>
                <h1 class="title">Weight:{{pet.Weight}}</h1>
                <h1 class="title">Health:{{pet.Health}}</h1>
                <h1 class="title">Health:{{pet.Health}}</h1>
                <h1 class="title">Location:{{pet.Location}}</h1>
                <h1 class="title">Contact:{{pet.Contact_No}}</h1>
                <h1 class="title">Description:{{pet.Description}}</h1>
                <h1 class="title">Price:{{pet.Price}} Rs</h1>
                <h1 class="title">Uploaded_at:{{pet.Uploaded_at}}</h1> 
            </div>
            <br>

            

            <a href="{% url 'seller:updatepetdetail' user.id pet.id %}"><button class="btn btn-primary" style="margin-left: 500px;font-size: 25px;">Edit</button></a>
            <span>
            <!-- Button to Open the Modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" style="font-size: 25px;">
                Delete
            </button>
            
            <!-- The Modal -->
            <div class="modal" id="myModal">
                <div class="modal-dialog">
                <div class="modal-content">
            
                    <!-- Modal Header -->
                    <!--<div class="modal-header">
                    <h4 class="modal-title">Modal Heading</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
            
                    <!-- Modal body -->
                    <div class="modal-body" style="font-size: 25px;">
                    Do you want to delete your account
                    </div>
            
                    <!-- Modal footer -->
                    <div class="modal-footer">
                    
                    <a href="{% url 'seller:deletepet' user.id pet.id %}" class="btn btn-danger">Delete</a>
                    </div>
            
                </div>
                </div>
            </div>
            </span>
            
            
        </div>



<!-- core  -->
<script src="{% static 'assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

<!-- bootstrap 3 affix -->
<script src="{% static 'assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

<!-- Meyawo js -->
<script src="{% static 'assets/js/meyawo.js' %}"></script>



</body>
</html>