adminapp/urls.py
from django.urls import path
from . import views
app_name='adminapp'
urlpatterns = [
    
    path('adminlogin', views.adminlogin, name='adminlogin'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('category', views.category, name='category'),
    path('showusers/', views.showusers, name='showusers'),
    path('viewcategories/', views.viewcategories, name='viewcategories'),
    path('showpets/', views.showpets, name='showpets'),
    path('adminupdatebuyer/<int:id>', views.adminupdatebuyer, name='adminupdatebuyer'),
    path('updatecategory/<int:id>', views.updatecategory, name='updatecategory'),
    path('deletecategory/<int:id>', views.deletecategory, name='deletecategory'),
    path(' admindeleteuser/<int:id>', views. admindeleteuser, name=' admindeleteuser'),
    path('admin_updatepet/<int:id>', views.admin_updatepet, name='adminupdatepet'),
    path('admin_deletepet/<int:id>',views.admin_deletepet,name='admin_deletepet'),
    path('adminlogout',views.adminlogout,name='adminlogout'),
]

costomer/urls.py
from django.urls import path
from . import views
app_name='costomer'
urlpatterns = [
    path('',views.index,name='index'),
    path('usersignup', views.usersignup, name='usersignup'),
    path('userlogin/', views.userlogin, name='userlogin'),
    path('userhome/<int:id>', views.userhome, name='userhome'),
    path('buyerhome/<int:id>', views.buyerhome, name='buyerhome'),
    path('updatebuyer/<int:id>',views.updatebuyer,name='updatebuyer'),
    path('changepasswordbuyer/<int:id>',views.changepasswordbuyer,name='changepasswordbuyer'),
    path('buyerlogout',views.buyerlogout,name='buyerlogout'),
    path('readcategory/<int:id>/<int:uid>',views.readcategory,name='readcategory'),
    path('viewprofile/<int:id>',views.viewprofile,name='viewprofile'),
    path('viewpetdetails2/<int:id>',views.viewpetdetails2,name='viewpetdetails2'),
    path('deleteuser/<int:id>',views.deleteuser,name='deleteuser'),
    path('mail/',views.mail,name='mail'),
]

critterville/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminapp.urls')),
    path('',include('costomer.urls')),
    path('',include('seller.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views
app_name='seller'
urlpatterns = [
    path('sellerhome/<int:id>',views.sellerhome,name='sellerhome'),
    path('updatepetdetail/<int:uid>/<int:pid>',views.updatepetdetail,name='updatepetdetail'),
    path('sellerlogout',views.sellerlogout,name='sellerlogout'),
    path('listed_products/<int:id>',views.listed_products,name='listed_products'),
    path('deletepet/<int:uid>/<int:pid>',views.deletepet,name='deletepet'),
    path('viewpetdetails/<int:uid>/<int:id>',views.viewpetdetails,name='viewpetdetails'),
]

costomer/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class SignUp(models.Model):
    FirstName=models.CharField(max_length=255)
    LastName=models.CharField(max_length=255)
    Phone_Number=models.CharField(max_length=15)
    Email=models.EmailField()
    Pass_word=models.CharField(max_length=15)

    def __str__(self):
        return self.FirstName
    
    


    

costomer/forms.py
from django import forms
from . models import SignUp

class UserSignUpForm(forms.ModelForm):
    Pass_word=forms.CharField(widget=forms.PasswordInput,max_length=10,min_length=2)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=10,min_length=2)

    class Meta():
        model=SignUp
        fields='__all__'

class UserLoginForm(forms.ModelForm):
    Pass_word=forms.CharField(widget=forms.PasswordInput,max_length=10,min_length=2)
    
    class Meta():
        model=SignUp
        fields=('Email','Pass_word')

class UpdateBuyerForm(forms.ModelForm):
    class Meta():
        model=SignUp
        fields=('FirstName','LastName','Phone_Number','Email')

class BuyerChangePasswordForm(forms.Form):
    OldPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    NewPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=2)

costomer/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import UserSignUpForm,UserLoginForm,UpdateBuyerForm,BuyerChangePasswordForm
from .models import SignUp
from seller.models import PetDetails
from adminapp.models import Category
from django.contrib import messages
from django.contrib.auth import logout as logouts
from critterville import settings
from django.core.mail import send_mail

# Create your views here.
def index(request):
    return render(request,'index.html')


def usersignup(request):
    if request.method=='POST':
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            firstname=form.cleaned_data['FirstName']
            lastname=form.cleaned_data['LastName']
            phonenumber=form.cleaned_data['Phone_Number']
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Pass_word']
            confirmpassword=form.cleaned_data['ConfirmPassword']

            user=SignUp.objects.filter(Email=email).exists()

            if user:
                messages.warning(request,"Already Exist")
                return redirect('/usersignup')
            elif password!=confirmpassword:
                messages.warning(request,"Mismatch")
                return redirect('/usersignup')
            else:
                tab = SignUp(FirstName=firstname, LastName=lastname, Phone_Number=phonenumber, Email=email, Pass_word=password)
                tab.save()
                messages.success(request,"")
                return redirect('/userlogin')
    else:
        form = UserSignUpForm()   
    return render(request,'usersignup.html', {'form':form})

def userlogin(request):
    if request.method=='POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Pass_word']
            try:
                user=SignUp.objects.get(Email=email)
                if not user:
                    messages.warning(request,"Enter a valid Email")
                    return redirect('/userlogin')
                elif password!=user.Pass_word:
                    messages.warning(request,"Incorrect Password")
                    return redirect('/userlogin')
                else:
                    messages.success(request,"")
                    return redirect('/userhome/%s' % user.id)
            except:
                messages.warning(request,"Username or Password Incorrect")
                return redirect('/userlogin')
    
    else:
        form=UserLoginForm()
    return render(request,'userlogin.html', {'form':form})



def userhome(request,id):
    user=SignUp.objects.get(id=id)
    return render(request,'userhome.html',{'user':user})


def buyerhome(request,id):
    user=SignUp.objects.get(id=id)
    category=Category.objects.all()
    return render(request,'buyerhome.html',{'user':user,'category':category})

def updatebuyer(request,id):
    user=SignUp.objects.get(id=id)
    if request.method=='POST':
        form=UpdateBuyerForm(request.POST or None,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,"")
            return redirect('/viewprofile/%s' % user.id)
    else:
        form=UpdateBuyerForm(instance=user)
    return render(request,'updatebuyer.html',{'user':user,'form':form})

def changepasswordbuyer(request,id):
    user=SignUp.objects.get(id=id)
    if request.method=='POST':
        form=BuyerChangePasswordForm(request.POST)
        if form.is_valid():
            oldpassword=form.cleaned_data['OldPassword']
            newpassword=form.cleaned_data['NewPassword']
            confirmpassword=form.cleaned_data['ConfirmPassword']
            if oldpassword!=user.Pass_word:
                messages.warning(request,"Incorrect")
                return redirect('/changepasswordbuyer/%s' % user.id)
            elif oldpassword==newpassword:
                messages.warning(request,"Similar")
                return redirect('/changepasswordbuyer/%s' % user.id)
            elif newpassword!=confirmpassword:
                messages.warning(request,"Mismatch")
                return redirect('/changepasswordbuyer/%s' % user.id)
            else:
                user.Pass_word=newpassword
                user.save()
                messages.success(request,"Success")
                return redirect('/buyerhome/%s' % user.id)
    else:
        form=BuyerChangePasswordForm()
    return render(request,'changepasswordbuyer.html',{'form':form,'user':user})

def buyerlogout(request):
    logouts(request)
    messages.success(request,"")
    return redirect('/')

def readcategory(request,id,uid):
    user=SignUp.objects.get(id=uid)
    category=Category.objects.all()
    cats=Category.objects.get(id=id)
    pro=PetDetails.objects.filter(Category=cats)
    return render(request,'readcategory.html',{'user':user,'cats':cats,'pro':pro,'category':category})

def viewpetdetails2(request,id):
    pet=PetDetails.objects.get(id=id)
    return render(request,'viewpetdetails2.html',{'pet':pet})

def viewprofile(request,id):
    user=SignUp.objects.get(id=id)
    return render(request,'viewprofile.html',{'user':user})

def deleteuser(request,id):
    user=SignUp.objects.get(id=id)
    user.delete()
    messages.success(request,"")
    return redirect('/')

def mail(request):
    if request.method=='POST':
        cname=request.POST.get('contact_name')
        cemail=request.POST.get('contact_email') 
        cmessage=request.POST.get('contact_message') 
        toemail="critterville123@gmail.com"  
        res=send_mail(cname,cmessage,settings.EMAIL_HOST_USER,[toemail],fail_silently=False)
        if(res==1):
            msg="Mail Sent Successfully"
        else:
            msg="Mail could not sent"
        return HttpResponse(msg)
    else:
        return render(request,'mail.html')
    

costomer/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<style>
    .dropdown {
    position: relative;
    display: inline-block;
    }

    .dropdown-content {
    display: none;
    position: absolute;
    width:130px;
    z-index: 1;
    background-color: rgb(202, 191, 191);
    }

    .dropdown:hover .dropdown-content {
    display: block;
    }

    .dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 20px;
    font-size: 16px;
    border: none;
    }

    .dropdown-content a {
    color:white;
    padding: 5px 5px;
    text-decoration: none;
    display: block;
   
    }

    .dropdown-content a:hover {
    background-color: transparent;
    }

       
  

</style>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <title>{% block title %}{% endblock %}Critterville</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Meyawo main styles -->
	<link rel="stylesheet" href="{% static 'assets/css/meyawo.css' %}">
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

    <!-- Page Navbar -->
    <nav class="custom-navbar" data-spy="affix" data-offset-top="20" style="background-color:rgb(202, 191, 191); height:70px;">
        
            <a class="logo" href="#" style="font-size: 40px; margin-left: 150px;">Critterville</a>         
            <ul class="nav">
                <li class="item">
                    <a class="active-menu" style="font-size: 20px;" href="{% url 'costomer:index' %}">Home</a>
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="#about" >About Us</a>
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="{% url 'costomer:usersignup' %}">Signup</a>
                </li>
                <li class="item">
                    <div class="dropdown">
                        <a class="link" style="font-size: 20px;" href="{% url 'costomer:userlogin' %}">Login</a>
                        <div class="dropdown-content" style="border:1px solid rgb(156, 153, 153);">
                            <a href="{% url 'adminapp:adminlogin' %}" style="font-size: 20px;">Admin Login</a>
                         </div>
                    </div>     
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="{% url 'costomer:mail' %}">Contact Us</a>
                </li>
                
            </ul>
            <a href="javascript:void(0)" id="nav-toggle" class="hamburger hamburger--elastic" style="margin-right:250px;">
                <div class="hamburger-box" style="color: black;">
                  <div class="hamburger-inner"></div>
                </div>
            </a>
         
           
    </nav><!-- End of Page Navbar -->
 

{% block content %}
 
{% endblock %}
    <!-- footer -->
    <div class="container">
        <footer class="footer">       
            <p class="mb-0">Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">DevCRUD</a></p>
            <div class="social-links text-right m-auto ml-sm-auto">
                <a href="javascript:void(0)" class="link"><i class="ti-facebook"></i></a>
                <a href="javascript:void(0)" class="link"><i class="ti-twitter-alt"></i></a>
                <a href="javascript:void(0)" class="link"><i class="ti-google"></i></a>
                <a href="javascript:void(0)" class="link"><i class="ti-pinterest-alt"></i></a>
                <a href="javascript:void(0)" class="link"><i class="ti-instagram"></i></a>
                <a href="javascript:void(0)" class="link"><i class="ti-rss"></i></a>
            </div>
        </footer>
    </div> <!-- end of page footer -->
	
	<!-- core  -->
    <script src="{% static 'assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

    <!-- bootstrap 3 affix -->
	<script src="{% static 'assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

    <!-- Meyawo js -->
    <script src="{% static 'assets/js/meyawo.js' %}"></script>

</body>
</html>

costomer/templates/buyerbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <style>
    .dropdown {
    position: relative;
    display: inline-block;
    }

    .dropdown-content {
    display: none;
    position:absolute;
    width:150px;
    z-index: 1;
    background-color: rgb(156, 182, 207);
    }

    .dropdown:hover .dropdown-content {
    display: block;
    }

    .dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 30px;
    font-size: 16px;
    border: none;
    }

    .dropdown-content a {
    color: white;
    padding: 5px 5px;
    text-decoration: none;
    display: block;
    }

    .dropdown-content a:hover {
    background-color: #f1f1f1;
    }

    .rounded-button {
        width: 60px;
        height: 60px;
        background:white;
        color: black;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        border-radius: 50%;
        border: 1 px dashed black;
        text-decoration: none;
        transition: background 0.2s;
        margin-left: 700px;
    }
    
    .rounded-button:hover {
        background: #00866c;
    }

    .icon{
        font-size: 25px;
        color: white;
        margin-right: 190;
        font-weight: 800;
    }
  </style>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <title>{% block title %}Welcome to Critterville{% endblock %}</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Meyawo main styles -->
	<link rel="stylesheet" href="{% static 'assets/css/meyawo.css' %}">
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

    <!-- Page Navbar -->
    <nav class="custom-navbar" data-spy="affix" data-offset-top="20" style="background-color:rgb(156, 182, 207); height:70px;">
        
            <a class="logo" href="#" style="font-size: 40px; margin-left: 150px;">Critterville</a>         
            <ul class="nav">
                <li class="item">
                    <a class="active-menu" style="font-size: 20px;" href="#">Home</a>
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="#categories" >Categories</a>
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="#about" >About Us</a>
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="{% url 'costomer:mail' %}">Contact Us</a>
                </li>
                <li class="item">
                    <div class="dropdown">
                        <a class="link" style="font-size: 20px;" href="#">Settings</a>
                        <div class="dropdown-content" style="border:1px solid rgb(76, 110, 139);">
                            
                            <a href="{% url 'costomer:viewprofile' user.id %}" style="font-size: 15px;">View profile</a>
                            <a href="{% url 'costomer:changepasswordbuyer' user.id %}" style="font-size: 15px;">Change Password</a>    
                            
                        </div>
                    </div>     
                </li>
                <li class="item">
                    <a class="link" style="font-size: 20px;" href="{% url 'costomer:buyerlogout' %}">Logout</a>
                </li>
                
                
            </ul>
            
            <a href="javascript:void(0)" id="nav-toggle" class="hamburger hamburger--elastic" style="margin-right:250px;">
                <div class="hamburger-box" style="color: black;">
                  <div class="hamburger-inner"></div>
                </div>
            </a>
            
           
    </nav><!-- End of Page Navbar -->


{% block content %}

{% endblock %}


 <!-- footer -->
 <div class="container">
    <footer class="footer">       
        <p class="mb-0">Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">DevCRUD</a></p>
        <div class="social-links text-right m-auto ml-sm-auto">
            <a href="javascript:void(0)" class="link"><i class="ti-facebook"></i></a>
            <a href="javascript:void(0)" class="link"><i class="ti-twitter-alt"></i></a>
            <a href="javascript:void(0)" class="link"><i class="ti-google"></i></a>
            <a href="javascript:void(0)" class="link"><i class="ti-pinterest-alt"></i></a>
            <a href="javascript:void(0)" class="link"><i class="ti-instagram"></i></a>
            <a href="javascript:void(0)" class="link"><i class="ti-rss"></i></a>
        </div>
    </footer>
</div> <!-- end of page footer -->

<!-- core  -->
<script src="{% static 'assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

<!-- bootstrap 3 affix -->
<script src="{% static 'assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

<!-- Meyawo js -->
<script src="{% static 'assets/js/meyawo.js' %}"></script>

</body>
</html>

costomer/templates/buyerhome.html
{% extends 'buyerbase.html' %}
{% load static %}
{% block content %}



<!-- page header -->
<header id="home" class="header" >           
            
        <img src="{% static 'assets/imgs/wallpaper6.jpg' %}" alt="imgs" style="width: 100%;
        height: 100%;
        object-fit: cover;" >
    
</header>
<!-- end of page header -->
<br><br>
   

  
    <!-- portfolio section -->
    <section class="section" id="categories">
        <div class="container text-center">
            <p class="section-subtitle"></p>
            <h6 class="section-title mb-6">Categories</h6>
            <!-- row -->
            <div class="row">
                {% for category in category %}
                <div class="col-md-4" >
                        <a href="{% url 'costomer:readcategory' category.id user.id %}" style="color: black;" class="portfolio-card">
                        
                        
                        <img src="{{category.Image.url}}" class="portfolio-card-img" style="height: 250px;" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, meyawo Landing page">    
                        <span class="portfolio-card-overlay">
                            <span class="portfolio-card-caption">
                                <h5>{{category.Name}}</h5>
                                <p class="font-weight-normal"></p>
                            </span>                         
                        </span>                     
                    </a>
                </div>
                {% endfor %}
                
            </div><!-- end of row -->
        </div><!-- end of container -->
    </section> <!-- end of portfolio section -->

<br><br><br>

    <!-- about section -->
    <section class="section pt-0" id="about">
        <!-- container -->
        <div class="container text-center">
            <!-- about wrapper -->
            <div class="about">
                <div class="about-img-holder">
                    <img src="{% static 'assets/imgs/wallpaper3.jpg' %}" class="about-img" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, meyawo Landing page">
                </div>
                <div class="about-caption">
                    <p class="section-subtitle"></p>
                    <br><br><br>
                    <h2 class="section-title mb-3">About Critterville</h2>
                    <p>
                        Critterville welcomes you to the ultimate online community for pet lovers! Our primary goal is to create a platform that connects pet owners worldwide, providing a broad range of services to support and enhance the well-being of their beloved pets.
                        <br><br>
                        At Critterville, we recognize that pets are not just animals but family members; therefore, we want to ensure they receive the best possible care. Our services are specifically designed to provide a wide range of resources for pet owners, including valuable advice, support, and tools that can assist pet owners in finding and connecting with other pet lovers.
                        <br><br>
                        Critterville also offers the Find Pets for Adoption service, which enables pet owners to search for a new furry friend to bring into their family. This service makes it easier to find and connect with pets available for adoption in your local area, providing a loving home for needy animals.
                        <br><br>
                        At Critterville, we are committed to providing the best possible service to our community of pet lovers. Our team is dedicated to offering a seamless experience and continuously updating our platform with exciting new features. 
                        <br><br>
                        Join Critterville today and become part of our pet-loving community!
                        <br><br>
                        Best,
                        <br>
                        Critterville Team

             
                    </p>
                    <a href="{% url 'costomer:userlogin' %}"><button class="btn-rounded btn btn-outline-primary mt-4">Join Now</button></a>
                </div>              
            </div><!-- end of about wrapper -->
        </div><!-- end of container -->
    </section> <!-- end of about section -->

    


{% endblock %}
   
     
    

    


   

costomer/templates/viewprofile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>{% block title %}Welcome to Critterville{% endblock %}</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Meyawo main styles -->
	<link rel="stylesheet" href="{% static 'assets/css/meyawo.css' %}">
     

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600&display=swap');

        *{
        font-family: 'Nunito', sans-serif;
        margin:0; padding:0;
        box-sizing: border-box;
        outline: none; border:none;
        text-decoration: none;
        transition: all .2s linear;
        text-transform: capitalize;
        }

        html{
        font-size: 62.5%;
        overflow-x: hidden;
        }

        body{
        background: #eee;
        }

        .container{
        max-width: 1200px;
        max-height: fit-content;
        margin:0 auto;
        padding:3rem 2rem;
        }

        .container .title{
        font-size: 3.5rem;
        color:#444;
        margin-bottom: 3rem;
        text-transform: uppercase;
        margin-left: 30px;
        }

        .container .title1{
        font-size: 3.5rem;
        color:#918d8c;
        margin-bottom: 3rem;
        text-transform: uppercase;
        margin-left: 30px;
        border-bottom: 1px solid rgb(168, 164, 164);
        }

        .container .products-container{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(30rem, 1fr));
        gap:2rem;
        }

        .container .products-container .product{
        text-align: center;
        padding:3rem 2rem;
        background: #fff;
        box-shadow: 0 .5rem 1rem rgba(0,0,0,.1);
        outline: .1rem solid #ccc;
        outline-offset: -1.5rem;
        cursor: pointer;
        }

        .container .products-container .product:hover{
        outline: .2rem solid #222;
        outline-offset: 0;
        }

        .container .products-container .product img{
        height: 25rem;
        }

        .container .products-container .product:hover img{
        transform: scale(.9);
        }

        .container .products-container .product h3{
        padding:.5rem 0;
        font-size: 2rem;
        color:#444;
        }

        .container .products-container .product:hover h3{
        color:#27ae60;
        }

        .container .products-container .product .price{
        font-size: 2rem;
        color:#444;
        }

        .button {
        background-color:white; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 25px;
        margin-left: 800px;
        cursor: pointer;
        
      }

      .button:hover {
        background-color: rgb(175, 163, 163);
      }


        @media (max-width:991px){

        html{
            font-size: 55%;
        }

        }

        @media (max-width:768px){

        .products-preview .preview img{
            height: 25rem;
        }

        }

        @media (max-width:450px){

        html{
            font-size: 50%;
        }

        }
    </style>



</head>
<body>
<br><br><br><br>
    <div class="container" style="background-color: white">
            
            <br><br>
            <div style="margin-left: 200px;border:1px solid  white;width:600px;background-color:white;">
                <h1 class="title" style="font-size: 70px;">{{user.FirstName}} {{user.LastName}} </h1>
                
                <h1 class="title" style="font-size: 40px;">Contact_No</h1>
                <h2 class="title1" style="font-size: 20px;">{{user.Phone_Number}}
                <h1 class="title" style="font-size: 40px;">EmailId</h1>
                <h2 class="title1" style="font-size: 20px;">{{user.Email}}
            </div>
    </div> 
    <br><br>
    <a href="{% url 'costomer:buyerhome' user.id %}"><button class="btn btn-primary" style="margin-left: 600px;font-size: 30px;">Back</button></a>
    <span>
        <a href="{% url 'costomer:updatebuyer' user.id %}"><button class="btn btn-primary" style="font-size: 30px;">Edit profile</button></a>
    </span> 
    <span>
         <!-- Button to Open the Modal -->
         <button type="button" data-toggle="modal" class="btn btn-primary" data-target="#myModal" style="font-size: 30px;">
            Delete
        </button>
        
        <!-- The Modal -->
        <div class="modal" id="myModal">
            <div class="modal-dialog">
            <div class="modal-content">
        
                <!-- Modal Header -->
                <!--<div class="modal-header">
                <h4 class="modal-title">Modal Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
        
                <!-- Modal body -->
                <div class="modal-body" style="font-size: 25px;">
                Do you want to delete your account
                </div>
        
                <!-- Modal footer -->
                <div class="modal-footer">
                
                <a href="{% url 'costomer:deleteuser' user.id %}" class="btn btn-danger">Delete</a>
                </div>
        
            </div>
            </div>
        </div>
    </span>  
 

<!-- core  -->

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

<script src="{% static 'assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

<!-- bootstrap 3 affix -->
<script src="{% static 'assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

<!-- Meyawo js -->
<script src="{% static 'assets/js/meyawo.js' %}"></script>



</body>
</html>