adminapp/adminapp/urls.py
from django.urls import path
from . import views
app_name='adminapp'
urlpatterns = [
    
    path('adminlogin', views.adminlogin, name='adminlogin'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('category', views.category, name='category'),
    path('showusers/', views.showusers, name='showusers'),
    path('showpets/', views.showpets, name='showpets'),
    path('adminupdatebuyer/<int:id>', views.adminupdatebuyer, name='adminupdatebuyer'),
    path(' admindeleteuser/<int:id>', views. admindeleteuser, name=' admindeleteuser'),
    path('admin_updatepet/<int:id>', views.admin_updatepet, name='adminupdatepet'),
    path('admin_deletepet/<int:id>',views.admin_deletepet,name='admin_deletepet'),
    path('adminlogout',views.adminlogout,name='adminlogout'),
]

adminapp/urls.py
from django.urls import path
from . import views
app_name='adminapp'
urlpatterns = [
    
    path('adminlogin', views.adminlogin, name='adminlogin'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('category', views.category, name='category'),
    path('showusers/', views.showusers, name='showusers'),
    path('viewcategories/', views.viewcategories, name='viewcategories'),
    path('showpets/', views.showpets, name='showpets'),
    path('adminupdatebuyer/<int:id>', views.adminupdatebuyer, name='adminupdatebuyer'),
    path('updatecategory/<int:id>', views.updatecategory, name='updatecategory'),
    path('deletecategory/<int:id>', views.deletecategory, name='deletecategory'),
    path(' admindeleteuser/<int:id>', views. admindeleteuser, name=' admindeleteuser'),
    path('admin_updatepet/<int:id>', views.admin_updatepet, name='adminupdatepet'),
    path('admin_deletepet/<int:id>',views.admin_deletepet,name='admin_deletepet'),
    path('adminlogout',views.adminlogout,name='adminlogout'),
]

critterville/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminapp.urls')),
    path('',include('costomer.urls')),
    path('',include('seller.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views
app_name='seller'
urlpatterns = [
    path('sellerhome/<int:id>',views.sellerhome,name='sellerhome'),
    path('updatepetdetail/<int:uid>/<int:pid>',views.updatepetdetail,name='updatepetdetail'),
    path('sellerlogout',views.sellerlogout,name='sellerlogout'),
    path('listed_products/<int:id>',views.listed_products,name='listed_products'),
    path('deletepet/<int:uid>/<int:pid>',views.deletepet,name='deletepet'),
    path('viewpetdetails/<int:uid>/<int:id>',views.viewpetdetails,name='viewpetdetails'),
]

adminapp/adminapp/models.py
from django.db import models

# Create your models here.

class Login(models.Model):
    UserName=models.CharField(max_length=255)
    Password=models.CharField(max_length=10)

class Category(models.Model):
    Name=models.CharField(max_length=50)
    Image = models.ImageField(upload_to='media/',null=True,blank=True)
    
    def __str__(self):
        return self.Name

adminapp/models.py
from django.db import models

# Create your models here.

class Login(models.Model):
    UserName=models.CharField(max_length=255)
    Password=models.CharField(max_length=10)

class Category(models.Model):
    Name=models.CharField(max_length=50)
    Image = models.ImageField(upload_to='media/',null=True,blank=True)
    
    def __str__(self):
        return self.Name

adminapp/adminapp/forms.py
from django import forms
from . models import Login,Category
from costomer.models import SignUp
from seller . models import PetDetails

class AdminLoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=10,min_length=2)
    class Meta():
        model=Login
        fields='__all__'

class CategoryForm(forms.ModelForm):
    class Meta():
        model=Category
        fields='__all__'

class AdminUpdateBuyerForm(forms.ModelForm):
    class Meta():
        model=SignUp
        fields=('FirstName','LastName','Phone_Number','Email')

class AdminUpdatePetForm(forms.ModelForm):
    class Meta():
        model=PetDetails
        fields='__all__'

adminapp/forms.py
from django import forms
from . models import Login,Category
from costomer.models import SignUp
from seller . models import PetDetails

class AdminLoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=10,min_length=2)
    class Meta():
        model=Login
        fields='__all__'

class CategoryForm(forms.ModelForm):
    class Meta():
        model=Category
        fields='__all__'

class UpdateCategoryForm(forms.ModelForm):
    class Meta():
        model=Category
        fields='__all__'

class AdminUpdateBuyerForm(forms.ModelForm):
    class Meta():
        model=SignUp
        fields=('FirstName','LastName','Phone_Number','Email')

class AdminUpdatePetForm(forms.ModelForm):
    class Meta():
        model=PetDetails
        fields='__all__'

adminapp/adminapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from . forms import AdminLoginForm,CategoryForm,AdminUpdateBuyerForm,AdminUpdatePetForm
from .models import Login
from costomer.models import SignUp
from seller.models import PetDetails
from django.contrib import messages
from django.contrib.auth import logout as logouts


# Create your views here.
def dashboard(request):
    return render(request,'dashboard.html')


def adminlogin(request):
    if request.method=='POST':
        form = AdminLoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['UserName']
            password=form.cleaned_data['Password']
            try:
                user=Login.objects.get(UserName=username)
                if username!="critterville":
                    messages.warning(request,"Enter a valid Username")
                    return redirect('/adminlogin')
                
                elif password!="crittervil":
                    messages.warning(request,"Incorrect Password")
                    return redirect('/adminlogin')
                
                else:
                    messages.success(request,"")
                    return redirect('/dashboard')
            except:
              messages.warning(request,"Username or Password Incorrect")
    else:
        form=AdminLoginForm()
    return render(request,'adminlogin.html', {'form':form})

def category(request):
    if request.method=='POST':
        form = CategoryForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            form.save()
    
    else:
        form = CategoryForm()
    return render(request,'category.html', {'form':form})

def showusers(request):
    user=SignUp.objects.all()
    return render(request,'showusers.html',{'user':user})



def adminupdatebuyer(request,id):
    user=SignUp.objects.get(id=id)
    form=AdminUpdateBuyerForm(request.POST or None,instance=user)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.success(request,"updated")
            return redirect('/showusers')
    else:
        form=AdminUpdateBuyerForm(instance=user)
    return render(request,'adminupdatebuyer.html',{'form':form})

def admindeleteuser(request,id):
    user=SignUp.objects.get(id=id)
    user.delete()
    messages.success(request,"Deleted")
    return redirect('/showusers')


def showpets(request):
    pet=PetDetails.objects.all()
    return render(request,'showpets.html',{'pet':pet})


def admin_updatepet(request,id):
    pet=PetDetails.objects.get(id=id)
    form=AdminUpdatePetForm(request.POST or None,request.FILES or None,instance=pet)
    if form.is_valid():
        form.save()
        messages.success(request,"updated")
        return redirect('/showpets')
    else:
        form=AdminUpdatePetForm(instance=pet)
    return render(request,'adminupdatepet.html',{'form':form})

def admin_deletepet(request,id):
    pet=PetDetails.objects.get(id=id)
    pet.delete()
    messages.success(request,"Deleted")
    return redirect('/showpets')

def adminlogout(request):
    logouts(request)
    messages.success(request,"Logged out successfully")
    return redirect('/')







    

adminapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from . forms import AdminLoginForm,CategoryForm,AdminUpdateBuyerForm,AdminUpdatePetForm,UpdateCategoryForm
from .models import Login,Category
from costomer.models import SignUp
from seller.models import PetDetails
from django.contrib import messages
from django.contrib.auth import logout as logouts


# Create your views here.
def dashboard(request):
    return render(request,'dashboard.html')


def adminlogin(request):
    if request.method=='POST':
        form = AdminLoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['UserName']
            password=form.cleaned_data['Password']
            try:
                user=Login.objects.get(UserName=username)
                if username!="critterville":
                    messages.warning(request,"Enter a valid Username")
                    return redirect('/adminlogin')
                
                elif password!="crittervil":
                    messages.warning(request,"Incorrect Password")
                    return redirect('/adminlogin')
                
                else:
                    messages.success(request,"")
                    return redirect('/dashboard')
            except:
              messages.warning(request,"Username or Password Incorrect")
    else:
        form=AdminLoginForm()
    return render(request,'adminlogin.html', {'form':form})

def category(request):
    if request.method=='POST':
        form = CategoryForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            form.save()
    
    else:
        form = CategoryForm()
    return render(request,'category.html', {'form':form})

def viewcategories(request):
    user=Category.objects.all()
    return render(request,'viewcategories.html',{'user':user})

def updatecategory(request,id):
    user=Category.objects.get(id=id)
    if request.method=='POST':
        form=UpdateCategoryForm(request.POST or None,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,"updated")
            return redirect('/viewcategories')
    else:
        form=UpdateCategoryForm(instance=user)
    return render(request,'updatecategory.html',{'user':user,'form':form})

def deletecategory(request,id):
    user=Category.objects.get(id=id)
    user.delete()
    messages.success(request,"Deleted")
    return redirect('/viewcategories')

def showusers(request):
    user=SignUp.objects.all()
    return render(request,'showusers.html',{'user':user})



def adminupdatebuyer(request,id):
    user=SignUp.objects.get(id=id)
    form=AdminUpdateBuyerForm(request.POST or None,instance=user)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            messages.success(request," ")
            return redirect('/showusers')
    else:
        form=AdminUpdateBuyerForm(instance=user)
    return render(request,'adminupdatebuyer.html',{'form':form})

def admindeleteuser(request,id):
    user=SignUp.objects.get(id=id)
    user.delete()
    messages.success(request," ")
    return redirect('/showusers')


def showpets(request):
    pet=PetDetails.objects.all()
    return render(request,'showpets.html',{'pet':pet})


def admin_updatepet(request,id):
    pet=PetDetails.objects.get(id=id)
    form=AdminUpdatePetForm(request.POST or None,request.FILES or None,instance=pet)
    if form.is_valid():
        form.save()
        messages.success(request," ")
        return redirect('/showpets')
    else:
        form=AdminUpdatePetForm(instance=pet)
    return render(request,'adminupdatepet.html',{'form':form})

def admin_deletepet(request,id):
    pet=PetDetails.objects.get(id=id)
    pet.delete()
    messages.success(request," ")
    return redirect('/showpets')

def adminlogout(request):
    logouts(request)
    messages.success(request,"")
    return redirect('/')







    

adminapp/templates/adminbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <title>{% block title %}Admin | Dashboard{% endblock %}</title>
   

    <style>
        * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}
body {
    
    min-height: 100vh;
}
a {
    text-decoration: none;
    
}
li {
    list-style: none;
}
h1,
h2 {
    color: #145c6e;
}
h3 {
    color: #ada3a3;
}
.btn {
    background: #145c6e;
    color: rgb(27, 26, 26);
    padding: 5px 10px;
    text-align: center;
}
.btn:hover {
    color: #fff;
    background: black;
    padding: 3px 8px;
    border: 2px solid #fff;
}
.title {
    display: flex;
    align-items: center;
    justify-content: space-around;
    padding: 15px 10px;
    margin-top: 10px;

    
}
table {
    padding: 10px;
    border-collapse: collapse;
    border: 1px solid black;
}
th,
td {
    text-align: left;
    padding: 20px;
    border: 1px solid black;
}
.side-menu {
    position: fixed;
    background: #141414;
    width: 20vw;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}
.side-menu .brand-name {
    height: 10vh;
    display: flex;
    align-items: center;
    justify-content: center;
}
.side-menu li {
    font-size: 24px;
    padding: 10px 40px;
    color: white;
    display: flex;
    align-items: center;
}
.side-menu a {
    font-size: 24px;
    padding: 10px 40px;
    color: white;
    display: flex;
    align-items: center;
}

.side-menu li:hover {
    background: rgb(114, 106, 106);
    color: #fff;
}
.container {
   
    right: 0;
    width: 80vw;
    height: 100vh;
    background: white;
}
.container .header {
    position: fixed;
    top: 0;
    right: 0;
    width: 80vw;
    height: 10vh;
    background: black;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    z-index: 1;
}
.container .header .nav {
    width: 90%;
    display: flex;
    align-items: center;
}
.container .header .nav .search {
    flex: 3;
    display: flex;
    justify-content: center;
}
.container .header .nav .search input[type=text] {
    border: none;
    background: #f1f1f1;
    padding: 10px;
    width: 50%;
}
.container .header .nav .search button {
    width: 40px;
    height: 40px;
    border: none;
    display: flex;
    align-items: center;
    justify-content: center;
}
.container .header .nav .search button img {
    width: 30px;
    height: 30px;
}
.container .header .nav .user {
    flex: 1;
    display: flex;
    justify-content: space-between;
    align-items: center;
}
.container .header .nav .user img {
    width: 40px;
    height: 40px;
}
.container .header .nav .user .img-case {
    position: relative;
    width: 50px;
    height: 50px;
}
.container .header .nav .user .img-case img {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
.container .content {
    position: relative;
    margin-top: 10vh;
    min-height: 90vh;
    background: #f1f1f1;
}
.container .content .cards {
    padding: 20px 15px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
}
.container .content .cards .card {
    width: 250px;
    height: 150px;
    background: white;
    margin: 20px 10px;
    display: flex;
    align-items: center;
    justify-content: space-around;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
.container .content .content-2 {
    min-height: 60vh;
    display: flex;
    justify-content: space-around;
    align-items: flex-start;
    flex-wrap: wrap;
}
.container .content .content-2 .recent-payments {
    min-height: 50vh;
    flex: 5;
    background: white;
    margin: 0 25px 25px 25px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    display: flex;
    flex-direction: column;
}
.container .content .content-2 .new-students {
    flex: 2;
    background: white;
    min-height: 50vh;
    margin: 0 25px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    display: flex;
    flex-direction: column;
}
.container .content .content-2 .new-students table td:nth-child(1) img {
    height: 40px;
    width: 40px;
}
@media screen and (max-width: 1050px) {
    .side-menu li {
        font-size: 18px;
    }
}
@media screen and (max-width: 940px) {
    .side-menu li span {
        display: none;
    }
    .side-menu {
        align-items: center;
    }
    .side-menu li img {
        width: 40px;
        height: 40px;
    }
    .side-menu li:hover {
        background: #f05462;
        padding: 8px 38px;
        border: 2px solid white;
    }
}
@media screen and (max-width:536px) {
    .brand-name h1 {
        font-size: 16px;
    }
    .container .content .cards {
        justify-content: center;
    }
    .side-menu li img {
        width: 30px;
        height: 30px;
    }
    .container .content .content-2 .recent-payments table th:nth-child(2),
    .container .content .content-2 .recent-payments table td:nth-child(2) {
        display: none;
    }
}
    </style>
</head>
<body>
    <div class="side-menu">
        <div class="brand-name">
            <h1>Administration</h1>
        </div>
        <ul>
            <li ><a href="{% url 'adminapp:dashboard' %}">&nbsp; <span>Dashboard</span></a> </li>
            <li><a href="{% url 'adminapp:category' %}">&nbsp;<span>Add Categories</span></a> </li>
            <li><a href="{% url 'adminapp:viewcategories' %}">&nbsp;<span>View Categories</span></a> </li>
            <li><a href="{% url 'adminapp:showusers' %}">&nbsp;<span>Showusers</span></a> </li>
            <li><a href="{% url 'adminapp:showpets' %}">&nbsp;<span>Showpets</span></a> </li>
        </ul>
    </div>
    <div class="container">
        <div class="header">
            <div class="nav">
                <h1 style="margin-left: 430px;">CRITTERVILLE</h1>
                    <a href="{% url 'adminapp:adminlogout' %}" class="btn" style="margin-left: 600px;">Logout</a>
                    
            </div>
        </div>
    
    

    {% block content %}


    {% endblock %}
</div>

</body>
</html>

adminapp/templates/adminlogin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <title>Admin{% block title %}{% endblock %}</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Meyawo main styles -->
    <link rel="stylesheet" href="{% static 'assets/css/meyawo.css' %}">
    <style>
        
         @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap');
        *{
            margin: 0;
            padding: 0;
            font-family: 'poppins',sans-serif;
        }
        section{
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            width: 100%;
            
            background-image: url('static/assets/imgs/wallpaper.jpg');
            background-position: center;
            background-size: cover;
        }
        .form-box{
            position: relative;
            width: 400px;
            height: 400px;
            background: transparent;
            border: 2px solid rgba(165, 149, 223, 0.5);
            border-radius: 20px;
            backdrop-filter: blur(15px);
            display: flex;
            justify-content: center;
            align-items: center;
            
        }
        h2{
            font-size: 2em;
            color:#fff;
            text-align: center;
            margin-top: 0px;
        }
        .inputbox{
            position: relative;
            margin: 30px 0;
            width: 310px;
            border-bottom: 2px solid #fff;
        }
        .inputbox label{
            position: absolute;
            top: 50%;
            left: 5px;
            transform: translateY(-50%);
            color: #fff;
            font-size: 1em;
            pointer-events: none;
            transition: .5s;
        }
        input:focus ~ label,
        input:valid ~ label{
        top: -5px;
        }
        .inputbox input {
            width: 100%;
            height: 50px;
            background: transparent;
            border: none;
            outline: none;
            font-size: 1em;
            padding:0 35px 0 5px;
            color: #fff;
        }
        .inputbox ion-icon{
            position: absolute;
            right: 8px;
            color: #fff;
            font-size: 1.2em;
            top: 20px;
        }
        .forget{
            margin: -15px 0 15px ;
            font-size: .9em;
            color: #fff;
            display: flex;
            justify-content: space-between;  
        }
        
        .forget label input{
            margin-right: 3px;
            
        }
        .forget label a{
            color: #fff;
            text-decoration: none;
        }
        .forget label a:hover{
            text-decoration: underline;
        }
        button{
            width: 100%;
            height: 40px;
            border-radius: 40px;
            background: #fff;
            border: none;
            outline: none;
            cursor: pointer;
            font-size: 1em;
            font-weight: 600;
        }
        .register{
            font-size: .9em;
            color: #fff;
            text-align: center;
            margin: 25px 0 10px;
        }
        .register p a{
            text-decoration: none;
            color: #fff;
            font-weight: 600;
        }
        .register p a:hover{
            text-decoration: underline;
        }
    </style>
  
</head>
<body>
    {% for msg in messages %}
        {{msg}}
    {% endfor %}

    <section>
        <div class="form-box">
            <div class="form-value">
                <form action="" method="POST">
                    <h2> Admin Login</h2>
                
                    {% csrf_token%}
                    <div class="inputbox">
                        <ion-icon name="person-outline"></ion-icon>
                        <input type="username" placeholder="UserName" name="UserName" required id="id_UserName">
                        
                    </div>
                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        <input type="password" placeholder="Password" name="Password" required id="Password">
                        
                    </div>
                    
                    <button>Submit</button>
                    
                </form>
            </div>
        </div>
    </section>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

adminapp/templates/adminupdatebuyer.html
{% extends 'adminbase.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>


<div class="container">
    <div class="content-2">
        <div class="row align-items-center">
            <div class="recent-payments">
                <div class="title" style="margin-left: 590px;font-size: 30px;">
                    <h2>Update User</h2>
                </div>
    
                <form action="" method="post" style="margin-left: 850px;font-size: 20px;">
                    {% csrf_token %} 
                    <table style="border: 0px;">
                        <tr>
                            {{form.as_table}}
                        </tr>
                    </table>
                    <br><br>
                    <input type="submit" value="Update" class="btn" style="margin-left: 150px;font-size: 20px;">
                </form>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>    
{% endblock %}

adminapp/templates/showpets.html
{% extends 'adminbase.html' %}
{% load static %}
{% block title %}Showpets{% endblock %}
{% block content %}
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>


<div class="container">
    <div class="content-2">
        <div class="row align-items-center">
    
            <div class="recent-payments">
                <div class="title" style="margin-left: 560px;">
                    <h2>Show Pets</h2>
                </div>
                <table style="margin-left: 400px;">
                    <tr>
                        <th>ID</th>
                        <th>Username</th>
                        <th>Name</th>                
                        <th>Category</th> 
                        <th>Breed</th>       
                        <th>Gender</th>               
                        <th>Age</th>               
                        <th>Size</th>               
                        <th>Weight</th>               
                        <th>Health</th>               
                        <th>Location</th>               
                        <th>Image1</th>               
                        <th>Image2</th>               
                        <th>Contact_No</th>               
                        <th>Description</th>               
                        <th>Price</th>               
                        <th>Uploaded_at</th>
                        <th colspan="2">Options</th>

                    </tr>
                    {% for pet in pet %}
                    <tr>
                        <td>{{pet.id}}</td>
                        <td>{{pet.Username}}</td>
                        <td>{{pet.Name}}</td>
                        <td>{{pet.Category}}</td>
                        <td>{{pet.Breed}}</td>
                        <td>{{pet.Gender}}</td>
                        <td>{{pet.Age}}</td>
                        <td>{{pet.Size}}</td>
                        <td>{{pet.Weight}}</td>
                        <td>{{pet.Health}}</td>
                        <td>{{pet.Location}}</td>
                        <td><img src="{{pet.Photo1.url}}" width="200px"></td>
                        <td><img src="{{pet.Photo2.url}}" width="200px"></td>
                        <td>{{pet.Contact_No}}</td>
                        <td>{{pet.Description}}</td>
                        <td>{{pet.Price}} Rs</td>
                        <td>{{pet.Uploaded_at}}</td>

                        <td><a class="btn" href="{% url 'adminapp:admin_deletepet' pet.id %}">Delete</a></td>
                        <td><a class="btn" href="{% url 'adminapp:adminupdatepet' pet.id %}">Update</a></td>
                        

                        
                    </tr>
                    {% endfor %}
                </table>
                 
                <br><br>
                <a href="{% url 'adminapp:dashboard'  %}" class="btn" style="margin-left: 1000px;">Back</a>
                <span><a href="{% url 'adminapp:showpets'  %}" class="btn">Save</a></span>
            </div>
        </div>
    </div>
</div>
        
   


{% endblock %}

adminapp/templates/showusers.html
{% extends 'adminbase.html' %}
{% load static %}
{% block title %}Show users{% endblock %}
{% block content %}
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>


<div class="container">
    
        <div class="row align-items-center">
    
            <div class="recent-payments">
                <div class="title" style="margin-left: 560px;">
                    <h2>Show Users</h2>
                </div>
                <table style="margin-left: 600px;">
                    <tr>
                        <th>ID</th>
                        <th>FirstName</th>        
                        <th>LastName</th>        
                        <th>Phone_Number</th>        
                        <th>Email</th>               
                        <th colspan="2">Options</th>               
                    </tr>
                    {% for user in user %}
                    <tr>
                        <td>{{user.id}}</td>
                        <td>{{user.FirstName}}</td>
                        <td>{{user.LastName}}</td>
                        <td>{{user.Phone_Number}}</td>
                        <td>{{user.Email}}</td>
                        <td><a class="btn" href="{% url 'adminapp:adminupdatebuyer' user.id %}">Update</a></td>
                        <td><a class="btn" href="{% url 'adminapp: admindeleteuser' user.id %}">Delete</a></td>
                    </tr>
                    {% endfor %}
                </table>
                    
                    <br><br>
                    <a href="{% url 'adminapp:dashboard'  %}" class="btn" style="margin-left: 1000px;">Back</a>
                    <span><a href="{% url 'adminapp:showusers'  %}" class="btn">Save</a></span>
            </div>
        </div>
    
</div>
        
   

{% endblock %}

adminapp/templates/viewcategories.html
{% extends 'adminbase.html' %}
{% load static %}
{% block title %}Categories{% endblock %}
{% block content %}
<br><br><br><br>
<br>
<br>


<div class="container">
    
        <div class="row align-items-center">
    
            <div class="recent-payments">
                <div class="title" style="margin-left: 560px;">
                    <h2>View Pet Categories</h2>
                </div>
                <table style="margin-left: 700px;">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>        
                        <th>Image</th>
                        <th colspan="2">Options</th>                      
                    </tr>
                    {% for user in user %}
                    <tr>
                        <td>{{user.id}}</td>
                        <td>{{user.Name}}</td>
                        <td><img src="{{user.Image.url}}" style="width:250px;height: 250px;"></td>
                        <td><a class="btn" href="{% url 'adminapp:updatecategory' user.id %}">Update</a></td>
                        <td><a class="btn" href="{% url 'adminapp:deletecategory' user.id %}">Delete</a></td>
                        
                    </tr>
                    {% endfor %}
                </table>
                <br><br>
                <a href="{% url 'adminapp:dashboard'  %}" class="btn" style="margin-left: 1000px;">Back</a>
                <span><a href="{% url 'adminapp:viewcategories'  %}" class="btn">Save</a></span>
                
            </div>
            <br><br><br><br>
            <br>
        </div>
</div>
        
   

   

{% endblock %}